FROM python:3.10.1-slim
RUN apt-get update -y && apt-get install build-essential curl vim -y
#timezone
RUN cp /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
    echo "Asia/Seoul" > /etc/timezone
ENV PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PYTHONUNBUFFERED=1
EXPOSE 8000
WORKDIR /workspace
RUN pip install --upgrade pip && pip install poetry
RUN poetry config virtualenvs.create false
CMD ["/bin/bash","scripts/start-dev.sh"]